### PR TITLE
Write and read candidate block

### LINKED ISSUE #7: Implement request-candidate-block procedure
**Describe the bug**
Request, provide and collect a candidate block routines are not currently supported. This makes it impossible to create a winning block on reaching consensus.

**Additional context**
Technically speaking, by extending MsgHandler for each step, it should be straightforward to collect a requested candidate.

### PR DESCRIPTION
**Pull request by goshawk-3**
fixes #7

### CODE REVIEW

File: src/agreement/aggr_agreement.rs [hunk 1]
```diff
@@ -19,39 +20,30 @@ use super::{accumulator, verifiers};
 pub(super) async fn verify(
     ru: &RoundUpdate,
     committees_set: Arc<Mutex<CommitteeSet>>,
-    msg: &Message,
+    hdr: &Header,
+    aggr: &AggrAgreement,
```
Comment (herr-seppia) [inline src/agreement/aggr_agreement.rs:24]: Would make sense to have this as &self and implementing this verify in AggrAgreement?

**Review by herr-seppia — APPROVED** [review]
LGTM

Just a nit
